name: train-test

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get --purge remove -y dvc
          pip install "git+https://github.com/iterative/dvc#egg=dvc[s3]"
          dvc --version
          git fetch --prune --unshallow
          

          pip install -r requirements.txt
          
          dvc repro
          ls -l 
          echo "METRICS DIFF HERE: "
          dvc metrics diff master --show-md >> report.md
          
          dvc plots show classes.csv --template confusion -x actual -y predicted --show-json >> vega.json
          
          echo "PLOT MADE, NOW CONVERT TO PNG"
          vl2png vega.json 
          
          #| cml-publish --md --title 'my image' >> report.md
          cml-send-github-check report.md 
        
