name: train-test

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get --purge remove -y dvc
          pip install "git+https://github.com/iterative/dvc#egg=dvc[s3]"
          dvc --version
          git fetch --prune --unshallow
          
          echo "HELLO" >> report.md 
          pip install -r requirements.txt
          
          dvc repro
          echo "METRICS DIFF HERE: "
          dvc metrics diff master 
          
         # dvc plots show classes.csv --template confusion -x actual -y predicted --show-json >> vega.json
         # vl2png vega.json | cml-publish --md --title 'my image' >> report.md
          
        
