name: train-test

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get --purge remove -y dvc
          pip install "git+https://github.com/iterative/dvc#egg=dvc[s3]"
          dvc --version
          
          
          pip install -r requirements.txt
          dvc repro
          dvc metrics diff HEAD^ --show-md >> report.md
          dvc plots show classes.csv --template confusion -x actual -y predicted --show-json >> vega.json
          vg2png vega.json | cml-publish --md 1 --title 'my image' >> report.md
          cml-send-github-check report.md
        
